### Get request that fetches all app statistics
GET http://localhost:8080/app-statistics/all
Content-Type: application/json

### Get reequest that fetches report app statistics
GET http://localhost:8080/app-statistics/report
Content-Type: application/json

{
  "type": 1,
  "startDate": "1397-01-01",
  "endDate": "1397-11-29"
}
###